#!/bin/bash
# Setup those vars at /etc/environment
# PASSPHRASE=
# GS_ACCESS_KEY_ID=
# GS_SECRET_ACCESS_KEY=
# GS_REMOTE=

PREFIX=${DUPLICITY_PREFIX:-/.snapshots/backup}
OUTPUT=${DUPLICITY_OUTPUT:-file:///backup/system}
export PASSPHRASE=${PASSPHRASE:-grfgcnffjbeq}

set -x
INCLUDE=(
  "/etc"
  "/usr/local"
  "/var/lib/"
  "/var/adm/"
  "/var/mail/"
)

EXCLUDE=(
  "/var/lib/lxcfs"
  "/var/lib/docker"
  "/var/lib/flatpak"
)

CACHE_DIR=/tmp/duplicity-cache
PERIOD=3M

INCLUDES_ARGS=
for path in "${INCLUDE[@]}"; do
  INCLUDES_ARGS="--include $PREFIX/$path $INCLUDES_ARGS"
done

EXCLUDES_ARGS=
for path in "${EXCLUDE[@]}"; do
  EXCLUDES_ARGS="--exclude $PREFIX/$path $EXCLUDES_ARGS"
done

if btrfs subvolume show /.snapshots/backup; then
  btrfs subvolume delete /.snapshots/backup
fi

btrfs subvolume snapshot -r / /.snapshots/backup

duplicity  --archive-dir $CACHE_DIR --full-if-older 1M $INCLUDES_ARGS $EXCLUDES_ARGS --exclude '**' $PREFIX/ $OUTPUT
duplicity remove-older-than $PERIOD $OUTPUT

btrfs subvolume delete /.snapshots/backup
