#!/bin/bash
# Setup those vars at /etc/environment
# PASSPHRASE=
# GS_ACCESS_KEY_ID=
# GS_SECRET_ACCESS_KEY=
# GS_REMOTE=

USE_BTRFS=${DUPLICITY_USE_BTRFS:-true}
PREFIX=${DUPLICITY_PREFIX:-/.snapshots/backup}
OUTPUT=${DUPLICITY_OUTPUT:-file:///run/media/backup/system}
export PASSPHRASE=${PASSPHRASE:-grfgcnffjbeq}

CACHE_DIR=/tmp/duplicity-cache
PERIOD=3M

set -x

if [ "$USE_BTRFS" = "true" ]; then
  if btrfs subvolume show /.snapshots/backup; then
    btrfs subvolume delete /.snapshots/backup
  fi

  btrfs subvolume snapshot / /.snapshots/backup
  mount --bind /run/media/backup/ /.snapshots/backup/run/
  mount --bind /dev/ /.snapshots/backup/dev/
  OUTPUT="file:///run/system/"
fi 

chroot $PREFIX /usr/bin/duplicity --archive-dir $CACHE_DIR --full-if-older 1M $INCLUDES_ARGS $EXCLUDES_ARGS --include-filelist /etc/system-backup.conf / $OUTPUT
duplicity remove-older-than $PERIOD $OUTPUT

if [ "$USE_BTRFS" = "true" ]; then
  umount /.snapshots/backup/run/
  umount /.snapshots/backup/dev/
  btrfs subvolume delete /.snapshots/backup
fi 

sync
